package com.architechz.project.models;

public enum Erole {
	ROLE_CLIENTEADM,
    ROLE_CLIENTEREPRE,
    ROLE_ADMIN,
    ROLE_GERENTEREG,
    ROLE_GERENTEGEN,
    ROLE_OPERADOR,
    ROLE_MECANICO,
    ROLE_CONDUCTOR,
    ROLE_CONDUCTORVIS,
    ROLE_PARTNER,
    ROLE_AGENTE
}
